### ISSUE TITLE
Crash on init

### ISSUE THREAD

**Issue by sschellhoff** [FrogSquare/GodotGoogleService#12]
I made a test project with two buttons. One for inizialization and one for login. I tried to test that at the app crashed. My test-script is really simple:

```
extends Node2D

var google = null

# init
func _on_Button_pressed(): 
	if OS.get_name() == "Android":
		google = Engine.get_singleton("GooglePlay");
		google.init(get_instance_id())
		append("init done")
	else:
		append("cannot init, no android device")
 # login
func _on_Button2_pressed():
	if OS.get_name() == "Android":
		if google == null:
			google.login()
			append("login done")
		else:
			append("cannot login, need to init first")
	else:
		append("cannot login, no android device")

```

The append method is just for debug output inside my app. So when i start the app and hit the init button, the app crashes. These is the logcat output:

```
03-10 10:35:22.457 27982 27982 E AndroidRuntime: FATAL EXCEPTION: main
03-10 10:35:22.457 27982 27982 E AndroidRuntime: Process: de.sschellhoff.gulptheflies_test, PID: 27982
03-10 10:35:22.457 27982 27982 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/FragmentActivity;
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.LifecycleActivity.isSupport(Unknown Source:7)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.LifecycleCallback.getFragment(Unknown Source:2)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.LifecycleCallback.getFragment(Unknown Source:7)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zaae.zaa(Unknown Source:1)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at com.google.android.gms.common.api.GoogleApi.<init>(Unknown Source:31)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at com.google.android.gms.common.api.GoogleApi.<init>(Unknown Source:51)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at com.google.android.gms.auth.api.signin.GoogleSignInClient.<init>(Unknown Source:3)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at com.google.android.gms.auth.api.signin.GoogleSignIn.getClient(Unknown Source:3)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at org.godotengine.godot.PlayService.init(PlayService.java:74)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at org.godotengine.godot.GooglePlay$1.run(GooglePlay.java:55)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6981)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.FragmentActivity" on path: DexPathList[[zip file "/data/app/de.sschellhoff.gulptheflies_test-_Fp3MHvQJ-CPg4y1XMoxZQ==/base.apk"],nativeLibraryDirectories=[/data/app/de.sschellhoff.gulptheflies_test-_Fp3MHvQJ-CPg4y1XMoxZQ==/lib/arm, /data/app/de.sschellhoff.gulptheflies_test-_Fp3MHvQJ-CPg4y1XMoxZQ==/base.apk!/lib/armeabi-v7a, /system/lib]]
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-10 10:35:22.457 27982 27982 E AndroidRuntime: 	... 17 more
```

I tried googling it but that didn't really helped me. What am i doing wrong? I am using the current Godot 3.1 rc

**Comment by sschellhoff** [comment]
Ok, for this, i had to add the support library as dependency. Maybe put that in your README.md. But there is the next problem. The sign in popup pops up and then the app crashs with:


```
03-10 11:57:17.222  9420  9420 D FrogSquare: Play Service Available.
03-10 11:57:17.229  9420  9420 D FrogSquare: Google::Initialized
03-10 11:57:17.230  9420  9420 D FrogSquare: Google not connected
03-10 11:57:19.340  9420  9420 D AndroidRuntime: Shutting down VM
03-10 11:57:19.341  9420  9420 E AndroidRuntime: FATAL EXCEPTION: main
03-10 11:57:19.341  9420  9420 E AndroidRuntime: Process: de.sschellhoff.gulptheflies, PID: 9420
03-10 11:57:19.341  9420  9420 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9001, result=-1, data=Intent { (has extras) }} to activity {de.sschellhoff.gulptheflies/org.godotengine.godot.Godot}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4584)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4626)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6981)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at org.godotengine.godot.Utils.get_debug(Utils.java:79)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at org.godotengine.godot.Utils.d(Utils.java:103)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at org.godotengine.godot.GooglePlay.onMainActivityResult(GooglePlay.java:141)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at org.godotengine.godot.Godot.onActivityResult(Godot.java:257)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7758)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4577)
03-10 11:57:19.341  9420  9420 E AndroidRuntime: 	... 11 more


```




edit:
After trying it several times, i got it initialized. But i cannot let the user start the app like 5 times to got this done. This error message looks like an internal problem with your service wrapper.
