### ISSUE TITLE
Unable to login after last bugfix

### ISSUE THREAD

**Issue by sschellhoff** [FrogSquare/GodotGoogleService#13]
There is a new error after your last fix. Now i am totally unable to login.
```
03-11 11:19:12.466 19740 19740 D FrogSquare: Play Service Available.
03-11 11:19:12.483 19740 19740 D FrogSquare: Google::Initialized
03-11 11:19:12.485 19740 19740 D FrogSquare: Google not connected
03-11 11:19:13.003 18378 18378 I SignInActivity: Transition from -1 to 0
03-11 11:19:16.650 18378 18378 I SignInActivity: Transition from 0 to 1
03-11 11:19:16.667 18378 18378 I SignInActivity: Transition from 1 to 3
03-11 11:19:16.718 18378 18378 I SignInActivity: Transition from 3 to 4
03-11 11:19:16.980 18378 18378 I SignInActivity: Transition from 4 to 5
03-11 11:19:16.999 18378 18378 I SignInActivity: Transition from 5 to 6
03-11 11:19:17.133 18378 18378 I SignInActivity: Transition from 6 to 11
03-11 11:19:17.134 18378 18378 W SignInActivity: onSignInFailed()...
03-11 11:19:17.134 18378 18378 W SignInActivity: Sign in failed during 6
03-11 11:19:17.134 18378 18378 W SignInActivity: ==> Returning non-OK result: 10002
03-11 11:19:17.381 19740 19740 D AndroidRuntime: Shutting down VM
03-11 11:19:17.385 19740 19740 E AndroidRuntime: FATAL EXCEPTION: main
03-11 11:19:17.385 19740 19740 E AndroidRuntime: Process: de.sschellhoff.gulptheflies, PID: 19740
03-11 11:19:17.385 19740 19740 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9001, result=0, data=Intent { (has extras) }} to activity {de.sschellhoff.gulptheflies/org.godotengine.godot.Godot}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4584)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4626)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6981)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at org.godotengine.godot.Utils.get_debug(Utils.java:79)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at org.godotengine.godot.Utils.d(Utils.java:103)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at org.godotengine.godot.GooglePlay.onMainActivityResult(GooglePlay.java:141)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at org.godotengine.godot.Godot.onActivityResult(Godot.java:257)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7758)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4577)
03-11 11:19:17.385 19740 19740 E AndroidRuntime: 	... 11 more

```

So the null point exception is still there. The user/me is not able to login. That seems to result in this exception.

**Comment by sschellhoff** [comment]
The first few lines seem to be permission problems. I played around with the needed permissions. With authentication, network state and internet permissions, the sign in failed during 6 error was gone. But the rest is still happening.
Means:
Google Initialized 
Google not connected
NullPointerException


Am i doing anything wrong with my build? I pulled your updated version, i called scons to prepare my android build, i went to platform/android/java and made the build with gradle.
The error seems to be there but i checked your fix and this should really fix this error.

**Comment by RameshRavone** [comment]
The problem is with the Utils.java file, are you using other modules from
FrogSquare is so can you copy the Utils.java from GodotGoogleService to
those module too.

**Comment by sschellhoff** [comment]
Thanks, i will do this. But it seems that the problem was on my side. I saw that the export templates didn't got updated. I don't know why. The compilation process says it worked, but i don't get the new apk. So the problem is somewhere else and the shown error message was from the old version.

**Comment by kings2000** [comment]
> 
> 
> The first few lines seem to be permission problems. I played around with the needed permissions. With authentication, network state and internet permissions, the sign in failed during 6 error was gone. But the rest is still happening.
> Means:
> Google Initialized
> Google not connected
> NullPointerException
> 
> Am i doing anything wrong with my build? I pulled your updated version, i called scons to prepare my android build, i went to platform/android/java and made the build with gradle.
> The error seems to be there but i checked your fix and this should really fix this error.

how do i add such permissions?.
